name: build

on: [push, pull_request]

jobs:
  linux:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:${{ matrix.r }}
    env:
      NOT_CRAN: true
    steps:
    - uses: actions/checkout@v1
    - name: Install apt-get dependencies
      run: |
        apt-get update
        apt-get install git ssh curl bzip2 libffi-dev libfontconfig1-dev libcairo2-dev libpng-dev -y
    - name: Install httpgd
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
    - name: Running Tests
      run: |
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'error')"

  macos:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
    runs-on: macos-latest
    env:
      NOT_CRAN: true
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: Install XQuartz
      run: brew cask install xquartz
    - name: Install required libraries
      run: brew install libpng
    - name: Install httpgd
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org', type = 'mac.binary.el-capitan')"
        Rscript -e "install.packages(c('Rcpp'), repos = 'https://cloud.r-project.org', type = 'source')"
        Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'mac.binary.el-capitan')"
    - name: Running Tests
      run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'error')"

  windows:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
    runs-on: windows-latest
    env:
      NOT_CRAN: true
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'devtools'), repos = 'https://cloud.r-project.org', type = 'win.binary')"
        Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'win.binary')"
    - name: Running Tests
      run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'error')"
